module.exports = {
    // user
    USER_UPDATE: 'USER_UPDATE',
    USER_LOGIN: 'USER_LOGIN',
    USER_LOGOUT: 'USER_LOGOUT',

    /* 
       hot 
    */

    // getByPage
    HOT_GETBYPAGE: 'HOT_GETBYPAGE',
    HOT_GETBYPAGE_SUCCESS: 'HOT_GETBYPAGE_SUCCESS',
    HOT_GETBYPAGE_FALIED: 'HOT_GETBYPAGE_FALIED',

    // refresh
    HOT_ONREFRESH: 'HOT_ONREFRESH',
    HOT_ONREFRESH_SUCCESS: 'HOT_ONREFRESH_SUCCESS',
    HOT_ONREFRESH_FAILED: 'HOT_ONREFRESH_FAILED',

    // getById
    HOT_GETBYID: 'HOT_GETBYID',
    HOT_GETBYID_SUCCESS: 'HOT_GETBYID_SUCCESS',
    HOT_GETBYID_FAILED: 'HOT_GETBYID_FAILED',

    // support
    HOT_SUPPORT: 'HOT_SUPPORT',
    HOT_SUPPORT_SUCCESS: 'HOT_SUPPORT_SUCCESS',
    HOT_SUPPORT_FAILED: 'HOT_SUPPORT_FAILED',

    // unSupport
    HOT_UNSUPPORT: 'HOT_UNSUPPORT',
    HOT_UNSUPPORT_SUCCESS: 'HOT_UNSUPPORT_SUCCESS',
    HOT_UNSUPPORT_FAILED: 'HOT_UNSUPPORT_FAILED',

    // delete
    HOT_DELETE: 'HOT_DELETE',
    HOT_DELETE_SUCCESS: 'HOT_DELETE_SUCCESS',
    HOT_DELETE_FAILED: 'HOT_DELETE_FAILED',
}