module.exports = {
    /* 
        user
     */

    // update
    USER_UPDATE: 'USER_UPDATE',
    USER_UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',
    USER_UPDATE_FAILED: 'USER_UPDATE_FAILED',

    //login
    USER_LOGIN: 'USER_LOGIN',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',

    //logout
    USER_LOGOUT: 'USER_LOGOUT',
    USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',
    USER_LOGOUT_FAILED: 'USER_LOGOUT_FAILED',

    /* 
       hot 
    */

    // getByPage
    HOT_GETBYPAGE: 'HOT_GETBYPAGE',
    HOT_GETBYPAGE_SUCCESS: 'HOT_GETBYPAGE_SUCCESS',
    HOT_GETBYPAGE_FALIED: 'HOT_GETBYPAGE_FALIED',

    // refresh
    HOT_ONREFRESH: 'HOT_ONREFRESH',
    HOT_ONREFRESH_SUCCESS: 'HOT_ONREFRESH_SUCCESS',
    HOT_ONREFRESH_FAILED: 'HOT_ONREFRESH_FAILED',

    // getById
    HOT_GETBYID: 'HOT_GETBYID',
    HOT_GETBYID_SUCCESS: 'HOT_GETBYID_SUCCESS',
    HOT_GETBYID_FAILED: 'HOT_GETBYID_FAILED',

    // support
    HOT_SUPPORT: 'HOT_SUPPORT',
    HOT_SUPPORT_SUCCESS: 'HOT_SUPPORT_SUCCESS',
    HOT_SUPPORT_FAILED: 'HOT_SUPPORT_FAILED',

    // unSupport
    HOT_UNSUPPORT: 'HOT_UNSUPPORT',
    HOT_UNSUPPORT_SUCCESS: 'HOT_UNSUPPORT_SUCCESS',
    HOT_UNSUPPORT_FAILED: 'HOT_UNSUPPORT_FAILED',

    // delete
    HOT_DELETE: 'HOT_DELETE',
    HOT_DELETE_SUCCESS: 'HOT_DELETE_SUCCESS',
    HOT_DELETE_FAILED: 'HOT_DELETE_FAILED',
}