module.exports = {
    //user
    USER_UPDATE: 'USER_UPDATE',
    USER_LOGIN: 'USER_LOGIN',
    USER_LOGOUT: 'USER_LOGOUT',

    //hot

    // getByPage
    HOT_GETBYPAGE: 'HOT_GETBYPAGE',
    HOT_GETBYPAGE_SUCCESS: 'HOT_GETBYPAGE_SUCCESS',
    HOT_GETBYPAGE_FALIED: 'HOT_GETBYPAGE_FALIED',

    //refresh
    HOT_ONREFRESH: 'HOT_ONREFRESH',
    HOT_ONREFRESH_SUCCESS: 'HOT_ONREFRESH_SUCCESS',
    HOT_ONREFRESH_FAILED: 'HOT_ONREFRESH_FAILED',

    HOT_GETBYID: 'HOT_GETBYID',
    HOT_SUPPORT: 'HOT_SUPPORT',
    HOT_UNSUPPORT: 'HOT_UNSUPPORT',
    HOT_DELETE: 'HOT_DELETE',
}